<div class="metro span12">
	<div class="metro-sections">
		<div id="section1" class="metro-section tile-span-4">
			<a class="tile wide app bg-color-purple" href="<?php echo $this->url('home/spd', array('controller' => 'shop', 'action' => 'index')) ?>">
				<div class="image-wrapper">
					<span class="icon icon-list-2"></span>
				</div>
				<span class="app-label">Shop</span>
			</a>
		</div>
</div> 