<form>
	<fieldset>
		<legend>Legend</legend>
		<label>Label name</label>
		<input type="text" class="datepicker" placeholder="Type something…">
		<span class="help-block">Example block-level help text here.</span>
		<label class="checkbox">
			<input type="checkbox"><span class="metro-checkbox">Check me out</span>
		</label>
		<button type="submit" class="btn">Submit</button>
	</fieldset>
</form>

<script type="text/javascript">
	jQuery('.datepicker').datepicker();
</script>